model_name_or_path: /fs-computility/niuyazhe/shared/xueyingyi/xueyingyi/llama/LLaMA-Factory/saves/keyevl-7b_Eimage_all
template: keye_vl
trust_remote_code: true
image_max_pixels: 262144
video_max_pixels: 16384
infer_backend: huggingface
